### PR TITLE
Executes $apply() only if doesn't have another in execution (blur)

### PR DESCRIPTION
**Pull request by ivamoto-murillo**
Some components, like datepickers or combo boxes or autocompletes, has $apply() in her codes to "apply" something. Like this, sometimes **angular-validation** needs apply something too.

When **angular-validation** applies something to some component and that component executes $apply() before the validation, an error is displayed in console: "$apply already in progress".

To correct this, just verify if $apply() is in progress. If it isn't in progress execute him. If it is in progress, doesn't execute him.

### CODE REVIEW

**Comment by hueitan** [comment]
yes, this is a known issue in AngularJS1.x, but unfortunately I have to accept this PR because there is no other round to do this 🤔

**Comment by ivamoto-murillo** [comment]
Eu tentei resolver isso em meu código de outras maneiras mas não obtive sucesso. É uma solução feia, eu sei :cry:

**Comment by ivamoto-murillo** [comment]
@hueitan, can you generate a new version from angular-validation with this correction? I need that in my project :smile:

**Comment by hueitan** [comment]
Please use your own fork repo for now, I will let you know when I bump a new version.

Hope this is fine.

**Pull request merged**
