### PR TITLE
Added support for dynamic default messages using functions.

### PR DESCRIPTION
**Pull request by scottadamsmith**
Allows for dynamic default messages so they can better articulate to the user what the validation requires. An example would be setting the default message for minlength and maxlength.

``` javascript
        var defaultMessageOverrides = {
            minlength: {
                error: function (element, attrs, param) {
                    return 'A minimum of  ' + param + ' characters is required.';
                }
            }
            , maxlength: {
                error: function (element, attrs, param) {
                    return 'A maximum of  ' + param + ' characters is required.';
                }
            }
        };
        $validationProvider.setDefaultMsg(defaultMessageOverrides);
```

### CODE REVIEW

**Comment by huei90** [comment]
Do you mind showing some examples for this change?

**Comment by scottadamsmith** [comment]
What are you looking for in an example? I included an example above showing the default error message for minlength and maxlength using a function. Is there something more specific you would like to see? Let me know and I'd be glad to provide it.

**Comment by scottadamsmith** [comment]
Just wondering if there is something else you need from me specifically or if there are any concerns with the implementation. I would like to get this merged in and point our app to the main project.

**Comment by scottadamsmith** [comment]
@huei90 Is this update not going to get merged in then?

**Comment by huei90** [comment]
@scottadamsmith Sorry for the late reply.

More things to do

1. add the usage in API.md
2. write the test spec

Do you want to add those, otherwise I will do it.

**Comment by scottadamsmith** [comment]
@huei90 I can do those things, no problem. I will try and get to them sometime this week. Thanks for getting back to me.

**Comment by huei90** [comment]
@scottadamsmith Thank you too, and sorry I'm having a busy month.

**Comment by huei90** [comment]
@scottadamsmith any update?

**Comment by scottadamsmith** [comment]
I have actually not had time to complete this in the time frame I originally stated. I may not get to this week either, but will try to get it done by end of next week.

**Comment by huei90** [comment]
@chuanxd you are silently here .... 😶

**Comment by scottadamsmith** [comment]
@hueitan Think I have everything in that you asked for. Let me know if there is anything else I can do to get this right.

**Comment by hueitan** [comment]
Yes Perfect @scottadamsmith I'm going to squash and merge it now.

**Comment by scottadamsmith** [comment]
@hueitan Do you when you plan to tag another release? Would like to notify someone they can switch back from my fork at that time.

**Comment by huei-tan-sociomantic** [comment]
I will tag v1.4.3 in this week or next week! and will ping you here 🍻

**Comment by hueitan** [comment]
I will tag v1.4.3 in this week or next week! and will ping you here 🍻

**Pull request merged**
